USB_VID = 0x303a
USB_PID = 0x81A3
USB_PRODUCT = "HD-WF2"
USB_MANUFACTURER = "Huidu"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 8MB

# disable some probably not useful features to ensure we have a little more ram available
CIRCUITPY_ESPCAMERA = 0
CIRCUITPY_AUDIOMP3 = 0

# ensure internal flash is used for circuitpython storage
INTERNAL_FLASH_FILESYSTEM = 1

QSPI_FLASH_FILESYSTEM = 1
SPI_FLASH_FILESYSTEM = 0

CIRCUITPY_USB_HID = 0
CIRCUITPY_USB_MSC = 1
